language: node_js
git:
  depth: 1
node_js:
- stable
before_install: 
- rm -rf node_modules/
- openssl aes-256-cbc -K $encrypted_50977c82cc25_key -iv $encrypted_50977c82cc25_iv -in deploy_key.enc -out deploy_key -d
script: bash ./deploy.sh
env:
  global:
  - ENCRYPTION_LABEL: "50977c82cc25"
  - COMMIT_AUTHOR_EMAIL: "gabriel@garox.org"